version: '3.8'

services:
  framepack:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-18111}:18111"  # Simplified port mapping (host:container)
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0  # Required for external access
      - GRADIO_SERVER_PORT=18111     # Explicit port declaration
      - GRADIO_ALLOW_FLAGGING=never
      - GRADIO_TEMP_DIR=/app/tmp
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7860 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
